### ISSUE TITLE
Memory use for open-end and open-begin problems with keep-internals option

### ISSUE THREAD

**Issue by jeffreymonaco** [DynamicTimeWarping/dtw-python#12]
* Python port of R's Comprehensive Dynamic Time Warp algorithm package version: 1.10.0
* Python version: 3.9.6
* Operating System: OS X, Linux Mint

### Description

I use the dtw-python package to find occurrences of (multivariate) events in time series. In some applications, the query has several hundred samples and the reference can be tens of thousands of samples.

The open-begin and open-end constraints permit impressive, time-efficient subsequence dynamic time warping to find exemplars of the event (defined by the query) in the much longer reference time series.

In general, it is quite nice to be able to view the per-step cost and warp path as provided in the dtw-python alignment object with the keep-internals boolean equal to True.

This all works as expected from a functional perspective, but memory issues occur when trying to run on certain systems that have memory constraints imposed by higher-level provisioning software. 

Conceptually, the question is ... can anything be done to provide a smaller alignment object memory footprint for such scenarios given that the N x M cost matrix (or matrices) require significant storage when M >> N and the cost/warping information outside the immediate domain of the refererence-to-query match submatrix is not of interest?

**Comment by tonigi** [comment]
Unfortunately, not with this implementation. There may be different (approximate) algorithms, but not in the scope of the package. You may, of course, subsample the timeseries; or process piecewise. Consider that the per-step cost and warp path *are* available even when keep internals is disabled.

**Comment by jeffreymonaco** [comment]
Thank you for the answer and suggestions.

Apologies for the imprecision of some of my description. I like the ability to overlay the warp path on heatmap-style plots of the cost matrix normalized to give a per-step cost along the actual warp path and the bounding rectangle defined by the indices (index1, index2).

I invested quite a bit of time in comparing dtw-python with other implementations, and I am much more confident in the correctness of dtw-python; its speed of computation, ability to handle multivariate problems, etc. are unmatched.

Regarding piecewise processing, this might be doable if I run a pass first with keep-internals FALSE and then narrow down on the vicinity of the solution found.

Great package all around and I have an answer to go forward

Thanks again!
