### ISSUE TITLE
R plot output

### ISSUE THREAD

**Issue by rb643** [DynamicTimeWarping/dtw-python#13]
Could not find a R specific repo so apologies for posting here.

I'm trying to integrate the dtw twoWay plot into a shiny dashboard but unfortunately keep getting API errors/mismatches when using renderPlot to get the output to a window. I assume this is because the dtw plot output is different from base or ggplot outputs and so I was curious if there is any way around this (rather then me trying to reinvent the plotting function into ggplot somehow..)

**Comment by tonigi** [comment]
It's done in base plot. The source code is in cran.

Il lun 19 lug 2021, 13:37 Richard ***@***.***> ha scritto:

**Comment by rb643** [comment]
Will dig into that, but if its already in base why wouldn't this work:
Running this on the server side
```
#server.r
output$dtwgen <- reactive({
    fits <- data[,input$select]

    out <- dtw(fits$t1,fits$t2,keep=TRUE)
    return(out)
    
  })
  
  output$dtw_plot <- renderPlot({
    out <- dtwgen()
    dtwPlotTwoWay(out)
  })
  
```
With this on ui.r side
```
tabPanel(
          title = "Dynamic Time Warp",
          withSpinner(
            plotOutput("dtw_plot"),
            type = 4,
            color = "#d33724",
            size = 0.7
          )
        )
```

Generates this...
```
Warning: Error in Cairo: Graphics API version mismatch
  129: Cairo
  128: <Anonymous>
  126: startPNG
  125: drawPlot
  111: <reactive:plotObj>
   95: drawReactive
   82: renderFunc
   81: output$dtw_plot_male
    1: runApp
```

**Comment by tonigi** [comment]
Graphics API version mismatch seems some technical quibble. In any case, the two-way plot is essentially out$index1 vs out$index2 .

**Comment by rb643** [comment]
Ah yeah seems to be a linux issue, works fine on the mac..
