### ISSUE TITLE
Improvement: Return figure in plot functions

### ISSUE THREAD

**Issue by capce** [DynamicTimeWarping/dtw-python#14]
Hey guys,
thanks for your great work here. I have a suggestion for little improvement. Maybe you could return the figure in addition to the axis?
https://github.com/DynamicTimeWarping/dtw-python/blob/6c21db2c946c794b06ed3c958b55ad8033b266f2/dtw/dtwPlot.py#L169
https://github.com/DynamicTimeWarping/dtw-python/blob/6c21db2c946c794b06ed3c958b55ad8033b266f2/dtw/dtwPlot.py#L207
This would be nice to work with the figure.

**Comment by tonigi** [comment]
Uhm... but given the axis, isn't it trivial to get the corresponding figure? To me it seems redundant.

**Comment by capce** [comment]
Okay you're right. I can do everything I had in mind with the axis.
