### ISSUE TITLE
ImportError: No module named stepPattern

### ISSUE THREAD

**Issue by nag92** [DynamicTimeWarping/dtw-python#2]
* Python port of R's Comprehensive Dynamic Time Warp algorithm package version: 1.0.4
* Python version: 2.7
* Operating System: 18.04

### Description

I am getting an error while running the quickstart
### What I Did
I tried to ruin the quick start code and I am getting an import error. 
```
Traceback (most recent call last):
  File "/home/nathaniel/stair_traj_learning/testing/dtw_testing.py", line 2, in <module>
    from dtw import dtw,rabinerJuangStepPattern
  File "/usr/local/lib/python2.7/dist-packages/dtw/__init__.py", line 16, in <module>
    from .dtw import *
  File "/usr/local/lib/python2.7/dist-packages/dtw/dtw.py", line 34, in <module>
    from dtw.stepPattern import *
ImportError: No module named stepPattern
```

**Comment by tcwalther** [comment]
Hi @nag92, I just tried this on my own machine, and it works as expected:

```
In [1]: from dtw.stepPattern import *
Importing the dtw module. When using in academic works please cite:
  T. Giorgino. Computing and Visualizing Dynamic Time Warping Alignments in R: The dtw Package.
  J. Stat. Soft., doi:10.18637/jss.v031.i07.
In [2]:
```

Make sure you don't have another package called `dtw` installed - my hunch is that you're accidentally importing the wrong package.

**Comment by tonigi** [comment]
Also: won't work in python2 .
