### ISSUE TITLE
Enquiry on warpArea Function

### ISSUE THREAD

**Issue by chankl3579** [DynamicTimeWarping/dtw-python#20]
* Python port of R's Comprehensive Dynamic Time Warp algorithm package version: 1.1.10
* Python version: 3.7
* Operating System: Windows

Thank you for sharing the repo. 
I am reading about the warpArea function, and have some questions. 

On the online documentation of this function, an example is provided. 
It is said that scipy.interpolate.interp1d would give result 6 because it would take average of the last few points in alignment. 
i.e. (3,3), (3,4), (3,5), (3,6), (3,7) would be averaged to (3,5) and the distance to diagonal is 7-5=2
But the warpArea function you design simply take the distance between (3,3) from alignment and (3,7) from diagonal line. 
Could you please explain why you design like this? 

Another question is that, if I exchange the reference sequence and query sequence of the example, the result is 6. 
I understand from the codes that this function is not really calculating the area between alignment and diagonal line, 
but still feel strange about it, Is it intentionally designed like this?

**Comment by tonigi** [comment]
It's a definition. Makes sense to me.
