### ISSUE TITLE
Incosistent output compared to pyts/tslearn

### ISSUE THREAD

**Issue by latorrefabian** [DynamicTimeWarping/dtw-python#21]
* Python port of R's Comprehensive Dynamic Time Warp algorithm package version: 1.1.12
* Python version: 3.8.9
* Operating System: MacOS 11.6.3

### Description

I am trying to compare the output from this package to that of tslearn and pyts

https://tslearn.readthedocs.io/en/stable/gen_modules/metrics/tslearn.metrics.dtw.html#tslearn.metrics.dtw
https://pyts.readthedocs.io/en/stable/generated/pyts.metrics.dtw.html

however I can't seem to make them match. tslearn and pyts give the same output with the following script. For dtw-python I have tried to change the metric from 'euclidean' to 'sqeuclidean' as well as taking the square root of the output, but most of the times the output does not match the alternatives.

### What I Did

```
import numpy as np
import math

import tslearn.metrics
import pyts.metrics

from dtw.dtw import dtw as dtw_fn

class DTW:
    def __init__(self):
        self.params = {'dtw_python': {}, 'tslearn': {}, 'pyts': {}}
        self.params['dtw_python']['dist_method'] = 'sqeuclidean'
        self.params['dtw_python']['step_pattern'] = 'asymmetric'
        self.params['dtw_python']['distance_only'] = True

        self.params['pyts']['return_path'] = False
        self.params['pyts']['method'] = 'classic'

    def _dtw_python(self, x, y):
        return dtw_fn(x, y, **self.params['dtw_python']).distance

    def _tslearn(self, x, y):
        return tslearn.metrics.dtw(x, y, **self.params['tslearn'])

    def _pyts(self, x, y):
        return pyts.metrics.dtw(x, y, **self.params['pyts'])


if __name__ == '__main__':
    dtw = DTW()
    x_test = np.array([1., -2., 1., 0])
    y_test = np.array([2., 1., 1., -1.])
    result_dtw = dtw._dtw_python(x_test, y_test)
    result_pyts = dtw._pyts(x_test, y_test)
    result_tslearn = dtw._tslearn(x_test, y_test)

    print('result dtw: ' + str(result_dtw))
    print('result pyts: ' + str(result_pyts))
    print('result tslearn: ' + str(result_tslearn))
```

**Comment by tonigi** [comment]
I recommend you to try and solve manually a small matrix such as the one in the dtw example or in the paper. I can't comment on the correctness of other implementations.

**Comment by tonigi** [comment]
However, note that in my package you are using the `asymmetric` step pattern (recursion). This doesn't seem the case for the other packages. Also `dist_method` is irrelevant for 1D timeseries.
