### ISSUE TITLE
Compare 2 audio with mfcc and show as percentage

### ISSUE THREAD

**Issue by rabihiawaludin** [DynamicTimeWarping/dtw-python#24]
* Python port of R's Comprehensive Dynamic Time Warp algorithm package version:
* Python version: 3
* Operating System: mac

### Description

Hey, i had try your code, i use feature extraction mfcc for audio han the result is array.
How to compare 2 array with dtw and show as percentage? can you give me example?

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by tonigi** [comment]
It's out of the scope of the package, sorry, especially unless you provide some reproducible code.
