### ISSUE TITLE
Consider warning on import, rather than printing citation info to stdout

### ISSUE THREAD

**Issue by williamgilpin** [DynamicTimeWarping/dtw-python#31]
Hello, thanks for this excellent package. In the current version, running

    import dtw

Leads to the following being placed in standard output

```
  Importing the dtw module. When using in academic works please cite:
    T. Giorgino. Computing and Visualizing Dynamic Time Warping Alignments in R: The dtw Package.
    J. Stat. Soft., doi:10.18637/jss.v031.i07.
```

I absolutely agree with the need to prompt users to cite sources, but printing this to standard output is somewhat unconventional compared to other Python projects based on published works. I am currently running a large benchmarking experiment, and I need to manually suppress this print statement every time I import a model that uses dtw internally.

Would you consider printing this using `warnings.warn`? In my opinion, that would be a bit more consistent with how other repos handle this issue. Warnings and exceptions are also a bit easier to manage than stdout. Thank you!

**Comment by tonigi** [comment]
That sounds a sensible suggestion, thanks.

**Comment by tonigi** [comment]
By the way I tried this technique to inhibit the message unless one is in interactive mode... I guess it's not working then? 

https://github.com/DynamicTimeWarping/dtw-python/blob/bdc4ea7a3d84cf5d09e07eff503d5090a72bd4f8/dtw/__init__.py#L31

https://stackoverflow.com/questions/2356399/tell-if-python-is-in-interactive-mode/2356427#2356427

**Comment by williamgilpin** [comment]
That's an interesting thread, I am getting the issue in my scripts, but that's probably on my end due to me not fully containing scope in my .py files. I bet that if I restructure my imports and `__main__()` then the issue will go away.

**Comment by tonigi** [comment]
My take-away message from that thread is that there is no "perfect" detection mechanism. For now I am updating it to `bool(getattr(sys, 'ps1', sys.flags.interactive))` which seems the least bad. I'll also probably change to warnings.
