### ISSUE TITLE
Suggestion: Remove the plt.show() calls in the plotting functions

### ISSUE THREAD

**Issue by RaverJay** [DynamicTimeWarping/dtw-python#32]
Hey there,

See title. This would allow the user to actually use the returned `ax` object, e.g. to plot more things into these Axes.
Currently the `plt.show()` command blocks this.

The usual pyplot way of things is to make the figure and axes, then plot stuff into it, customize the ticks etc, and then finally call
`plt.show()` or `plt.savefig()` - as the user's responsibility.

Also, it would be great to have more parameters, e.g. for figure size

Cheers

**Comment by tonigi** [comment]
I'm a bit baffled by the matplotlib library, but that sounds right. However, it would be a (small) breaking change, so I'm deferring it to the next major release.

**Comment by tonigi** [comment]
FWIW https://github.com/DynamicTimeWarping/dtw-python/commit/0698942da33230bcefbc45a3ffa0bebc262c5d4f

**Comment by tonigi** [comment]
Now in 1.3.0
