### ISSUE TITLE
Using open begin together with rigid step pattern disallows matching on first reference element (Both Python and R) 

### ISSUE THREAD

**Issue by daniellemccool** [DynamicTimeWarping/dtw-python#36]
* Python port of R's Comprehensive Dynamic Time Warp algorithm package version: 1.3.1
* Python version: 3.8.13
* Operating System: Win64

### Description

Both in R and Python, the implementation of open begin combined with the implementation of the rigid step pattern prevents alignment on the first element of the reference series. As far as I can tell from the literature, this is an unintended consequence.  Other step patterns don't have this problem.

I'm primarily an R user, so I'll explain where it comes from using the R code, but because it works the same in Python, this holds there as well. 

Adding the initial row of 0 to the distance matrix/cost matrix is done to account for all the other step matrices that look further back (from dtw.R)
```
if (open.begin) {
        if (is.na(norm) || norm != "N") {
            stop("Open-begin requires step patterns with 'N' normalization (e.g. asymmetric, or R-J types (c)). See papers in citation().")
        }
        lm <- rbind(0, lm)
        np <- n + 1
        precm <- matrix(NA, nrow = np, ncol = m)
        precm[1, ] <- 0
    }
```

For `query <- c(1, 2, 3, 4); ref <- c(1, 2, 3, 4, 5, 6)`  the `lm` following from the above looks like this
```
# >     [,1] [,2] [,3] [,4] [,5] [,6]
# > [1,]    0    0    0    0    0    0
# > [2,]    0    1    2    3    4    5
# > [3,]    1    0    1    2    3    4
# > [4,]    2    1    0    1    2    3
# > [5,]    3    2    1    0    1    2
```

Which is then passed to `globalCostMatrix()` with the rigid step pattern 

```
# >      [,1] [,2] [,3] [,4]
# > [1,]    1    1    1   -1
# > [2,]    1    0    0    1 
```

And produces this costMatrix and directionMatrix:
```
# > $costMatrix
# >      [,1] [,2] [,3] [,4] [,5] [,6]
# > [1,]    0    0    0    0    0    0
# > [2,]   NA    1    2    3    4    5
# > [3,]   NA   NA    2    4    6    8
# > [4,]   NA   NA   NA    3    6    9
# > [5,]   NA   NA   NA   NA    4    8

# > $directionMatrix
# >      [,1] [,2] [,3] [,4] [,5] [,6]
# > [1,]   NA   NA   NA   NA   NA   NA
# > [2,]   NA    1    1    1    1    1
# > [3,]   NA   NA    1    1    1    1
# > [4,]   NA   NA   NA    1    1    1
# > [5,]   NA   NA   NA   NA    1    1
```

I assume this can be fixed either on the initial distance/cost matrix handling, or on the rigid step pattern implementation. I don't know which is better. For me, since I'm only using the rigid step pattern, I made the following change, but it almost certainly will have unintended consequences with other step patterns:

```
if (open.begin) {
        if (is.na(norm) || norm != "N") {
            stop("Open-begin requires step patterns with 'N' normalization (e.g. asymmetric, or R-J types (c)). See papers in citation().")
        }
#        lm <- rbind(0, lm)
#        np <- n + 1
        np <- n
#        precm <- matrix(NA, nrow = np, ncol = m)
        precm <- matrix(NA, nrow = n, ncol = m)
#        precm[1, ] <- 0
        precm[1, ] <- lm[1, ]
    }
```

### What I Did

It's easy to see the behavior with the following:

```
from dtw import *
import numpy as np
query = [1, 2, 3, 4]
reference = [1, 2, 3, 4, 5, 6]
alignment = dtw(query, reference, open_end=True, open_begin=True, step_pattern=rigid)
alignment.index1
alignment.index2
```

**Comment by tonigi** [comment]
Gosh! Thanks for finding this subtle case. I may have implemented a fix, to appear in cran with release 1.23-1 any time now. The python version will come later. Please test if the results make sense.

**Comment by tonigi** [comment]
Closing this, I assume the new version fixed the issue.

**Comment by daniellemccool** [comment]
I work with a closed system that only updates the package versions twice a year, so this is the first time I've taken a look at the newer version. It doesn't seem to be fixed, but it's possible I misunderstand how DTW ought to work in this situation. 

```{r}
query <- c(1, 2, 3, 4); ref <- c(1, 2, 3, 4, 5, 6) # Expect alignment at element 1
res <- dtw(query, ref, open.end = TRUE, open.begin = TRUE, step.pattern = rigid) 

# index1 matched elements: indices in x
res$index1
# > [1] 2 3 4
# index2 corresponding mapped indices in y
res$index1
# > [1] 2 3 4
```
The first element in the query therefore doesn't have a match listed. If I change the reference to induce alignment at other than the first element:

```{r}
query <- c(1, 2, 3, 4); ref <- c(0, 1, 2, 3, 4, 5, 6)
res <- dtw(query, ref, open.end = TRUE, open.begin = TRUE, step.pattern = rigid)
# > res$index1
# [1] 1 2 3 4
# > res$index2
# [1] 2 3 4 5
```
