### ISSUE TITLE
dtw() got an unexpected keyword argument 'dist_method'

### ISSUE THREAD

**Issue by janinerugayan** [DynamicTimeWarping/dtw-python#38]
* Python port of R's Comprehensive Dynamic Time Warp algorithm package version:
* Python version: 3.10.6
* Operating System: 

### Description

I'm trying to calculate dtw using cosine distance as the method for the local distance. However, it's giving me an error with dtw lastest version 1.3.0. 

I installed previous version 1.1.14 and there was no issue. 

### What I Did

```
alignment = dtw(x=output_mean_hypothesis, y=output_mean_reference, dist_method="cosine", keep_internals=True)

TypeError: dtw() got an unexpected keyword argument 'dist_method'
```

**Comment by tonigi** [comment]
Works here. Please provide a full example and dtw-python version.
