### ISSUE TITLE
dtw.dtw doesn't work if one of the mfcc's row number is 1

### ISSUE THREAD

**Issue by zhu-yifang** [DynamicTimeWarping/dtw-python#48]
**Describe the bug**
dtw.dtw doesn't work if one of the mfcc's row number is 1.

**To Reproduce**
1. have 2 mfcc sequences, and one of them has row number 1.
2. call dtw.dtw on them.
3. it will say raise ValueError('XA and XB must have the same number of columns '
ValueError: XA and XB must have the same number of columns (i.e. feature dimension.)

Please provide a **self-contained** example. A colab may also be ok.

**Version**
Please state the version of dtw-python (as reported by pip or conda).
1.3.0

**Comment by tonigi** [comment]
Please provide example code. However, the error message probably reflects the problem.
