### ISSUE TITLE
rabinerJuangStepPattern

### ISSUE THREAD

**Issue by RodolfoDollinger** [DynamicTimeWarping/dtw-python#5]
Hello Tonigi,

I am testing both dtw libraries(R and Python), and I noticed that when I use rabinerJuangStepPattern I get different results for index values. Including the length of the vectors. But the distance value is egual for both versions. If I dont set the step_pattern, the results of the index values is the same.
I am considering the index differences between both languages.

Python Code:

import numpy as np
from dtw import *
idx = np.linspace(0,6.28,num=100)
query = np.sin(idx)

idx1 = np.linspace(0,6.28,num=70)
template = np.cos(idx1) + 0.5

alignment = dtw(query, template,
                step_pattern=rabinerJuangStepPattern(ptype=4,slope_weighting="c"),
                keep_internals=True,open_end=False, open_begin=False)
dist = alignment.distance
teste = alignment.index2

dist = 52.9795
test = [ 0  2  4  6  8 10 12 14 16 14 16 15 16 15 16 17 16 17 16 17 16 17 16 17
 16 17 16 17 16 17 16 17 16 17 16 17 16 17 16 17 16 17 16 17 16 17 16 17
 16 17 16 17 16 17 16 17 16 17 16 17 18 17 18 19 18 19 20 19 20 21 20 21
 22 21 22 23 22 23 24 23 24 25 24 25 26 25 26 27 26 27 28 30 31 33 35 33
 35 34 35 34 35 36 35 36 35 36 37 36 37 36 37 36 37 38 37 38 37 38 39 38
 39 38 39 38 39 40 39 40 39 40 41 40 41 40 41 42 41 42 43 42 43 45 47 49
 51 53 55 57 59 61 63 65 67 69]

len(test) = 154
________________________________________________________________________________________________
R Code:

library(dtw)

idx<-seq(0,6.28,len=100)
query<-sin(idx)

idx1 <- seq(0,6.28,len=70)
template<-cos(idx1) + 0.5

alignment<-dtw(query,template, keep=TRUE,step.pattern = rabinerJuangStepPattern(type=4,
                                                                                slope.weighting='c'),
                                                                                open.begin = FALSE, open.end = FALSE)
dist <- alignment$distance
index <- alignment$index2

dist = 52.9795

index = [1]  0  1  1  2  2  3  3  4  4  5  5  6  6  7  7  8  8  9  9 10 10 11 11 12 12 13 13 14 14 15 15
 [32] 16 16 17 17 18 18 19 19 20 20 21 21 22 22 23 23 24 24 25 25 26 26 27 27 28 28 29 29 30 30 31
 [63] 31 32 32 33 33 34 34 35 35 36 36 37 37 38 38 39 39 40 40 41 41 42 42 43 43 45 47 49 51 53 55
 [94] 57 59 61 63 65 67 69

length(index) = 100

**Comment by tonigi** [comment]
Sorry, somehow github messages got lost for your pull request. Thanks for the thorough example and PR! Commit 0c55feb should fix it.
