### ISSUE TITLE
I have two audios, how can I find the repetitions of them using dtw?

### ISSUE THREAD

**Issue by zouhan6806504** [DynamicTimeWarping/dtw-python#67]
suppose these two audios is 5mins mono 16k wav format. 
I load them with librosa
```
y, sr = librosa.load('E:/audio/113987.wav', sr=None)
y2, sr2 = librosa.load('E:/audio/101658.wav', sr=None)
```
then get mfcc features
```
mfcc1 = librosa.feature.mfcc(y, sr)
mfcc21 = librosa.feature.mfcc(y21, sr2)
```
both of the features shape (20, 9376)  (n_features, n_timesteps)

so, what I do next to get the repetitions of them?

**Comment by tonigi** [comment]
Uhm, not a DTW standard feature. You would need to build upon the library.
