### ISSUE TITLE
ValueError: No warping path found compatible with the local constraints

### ISSUE THREAD

**Issue by alla15747** [DynamicTimeWarping/dtw-python#8]
I got this error!

 43     dtw1 = dtw(template, query, keep_internals=True,window_type="sakoechiba",window_args={"window_size":w})
     44     #time_elapsed = (time.clock() - time_start)
     45     my_dict[i,str(w)] = [dtw1.normalizedDistance, dtw1.distance]

1 frames
/usr/local/lib/python3.6/dist-packages/dtw/dtw.py in dtw(x, y, dist_method, step_pattern, window_type, window_args, keep_internals, distance_only, open_end, open_begin)
    416 
    417     if numpy.isnan(gcm.distance):
--> 418         _error("No warping path found compatible with the local constraints")
    419 
    420     if step_pattern.hint != "NA":

/usr/local/lib/python3.6/dist-packages/dtw/dtw.py in _error(s)
    474 # Kludge because lambda: raise doesn't work
    475 def _error(s):
--> 476     raise ValueError(s)

ValueError: No warping path found compatible with the local constraints

**Comment by tonigi** [comment]
Please provide a reproducible example. It usually means that the constraints (in this case the Sakoe-Chiba band) do not allow any solution.

**Comment by pushkar5586** [comment]
I got the same error; had NaNs in my series. Setting NaNs to zero resolved the error.
