### ISSUE TITLE
"asymmetricP0" without the vertical move?

### ISSUE THREAD

**Issue by hbredin** [DynamicTimeWarping/dtw-python#82]
I'd like to build a step pattern similar to `asymmetricP0` but without the vertical move, like the image below:

![image](https://github.com/DynamicTimeWarping/dtw-python/assets/1080837/18962d77-e27a-411f-a7b2-afa049ab1a75)

How would you recommend I do that?

**Comment by tonigi** [comment]
Try this... 

```
from dtw.stepPattern import _P,  _c

asymmetric1 = StepPattern(_c(
    1, 1, 0, -1,
    1, 0, 0, 1,
    2, 1, 1, -1,
    2, 0, 0, 1,
), "N");
```

Hence

```
> print(asymmetric1)
Step pattern recursion:
 g[i,j] = min(
     g[i-1,j  ] +     d[i  ,j  ] ,
     g[i-1,j-1] +     d[i  ,j  ] ,
 ) 

Normalization hint: N
```
