### ISSUE TITLE
numpy issue 

### ISSUE THREAD

**Issue by aazz7777** [DynamicTimeWarping/dtw-python#91]
**Describe the bug**

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
**To Reproduce**

*Important:* Please provide a self-contained example. A colab may also be ok.

**Version**
Please state the version of dtw-python (as reported by pip or conda).:1.1.6

is it the version issue?

**Comment by tonigi** [comment]
We are at version 1.4.2... in any case it's a warning.
